#
# ppp top level makefile for Solaris 2
#
# $Id: Makefile.top,v 1.2 1995/06/01 02:23:09 paulus Exp $
#

BINDIR = /usr/local/bin
MANDIR = /usr/local/man
ETCDIR = /etc/ppp

INSTALL= /usr/sbin/install

all:
	cd chat; $(MAKE) all
	cd pppd; $(MAKE) all
	cd pppstats; $(MAKE) all
	cd svr4; $(MAKE) all

install: $(BINDIR) $(MANDIR)/man8 install-progs install-etcppp

install-progs:
	cd chat; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd pppd; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd pppstats; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd svr4; $(MAKE) BINDIR=$(BINDIR) install

install-etcppp: $(ETCDIR) $(ETCDIR)/options $(ETCDIR)/pap-secrets \
	$(ETCDIR)/chap-secrets

$(ETCDIR)/options:
	if netstat -rn | grep default >/dev/null; then \
	  cp etc.ppp/options $@; \
	else cp etc.ppp/options.leaf $@; fi
	chmod go-w $@
$(ETCDIR)/pap-secrets:
	$(INSTALL) -f $(ETCDIR) -m 600 etc.ppp/pap-secrets
$(ETCDIR)/chap-secrets:
	$(INSTALL) -f $(ETCDIR) -m 600 etc.ppp/chap-secrets

$(BINDIR):
	$(INSTALL) -d -m 755 $@
$(MANDIR)/man8:
	$(INSTALL) -d -m 755 $@
$(ETCDIR):
	$(INSTALL) -d -m 755 $@

clean:
	rm -f *~
	cd chat; $(MAKE) clean
	cd pppd; $(MAKE) clean
	cd pppstats; $(MAKE) clean
	cd svr4; $(MAKE) clean

