#
# ppp top level makefile for Solaris 2
#
# $Id: Makefile.top,v 1.4 1996/09/14 05:12:31 paulus Exp $
#

BINDIR = /usr/local/bin
MANDIR = /usr/local/man
ETCDIR = /etc/ppp

INSTALL= /usr/sbin/install

all:
	cd chat; $(MAKE) all
	cd pppd; $(MAKE) all
	cd pppstats; $(MAKE) all
	cd svr4; $(MAKE) all

install: $(BINDIR) $(MANDIR)/man8 install-progs install-etcppp

install-progs:
	cd chat; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd pppd; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd pppstats; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd svr4; $(MAKE) BINDIR=$(BINDIR) install

install-etcppp: $(ETCDIR) $(ETCDIR)/options $(ETCDIR)/pap-secrets \
	$(ETCDIR)/chap-secrets

$(ETCDIR)/options:
	cp etc.ppp/options $@
	chmod go-w $@
$(ETCDIR)/pap-secrets:
	$(INSTALL) -f $(ETCDIR) -m 600 etc.ppp/pap-secrets
$(ETCDIR)/chap-secrets:
	$(INSTALL) -f $(ETCDIR) -m 600 etc.ppp/chap-secrets

$(BINDIR):
	mkdir -m 755 -p $@
$(MANDIR)/man8:
	mkdir -m 755 -p $@
$(ETCDIR):
	mkdir -m 755 -p $@

clean:
	rm -f *~
	cd chat; $(MAKE) clean
	cd pppd; $(MAKE) clean
	cd pppstats; $(MAKE) clean
	cd svr4; $(MAKE) clean

