#
# pppdump Makefile for SVR4 systems
# $Id: Makefile.sol2,v 1.2 1999/09/22 23:57:57 masputra Exp $
#

include ../svr4/Makedefs

CFLAGS= $(COPTS) -I../include/net
OBJS = pppdump.o bsd-comp.o deflate.o zlib.o

all:	pppdump

pppdump: $(OBJS)
	$(CC) -o pppdump $(OBJS)

clean:
	rm -f $(OBJS) pppdump *~

install:
	$(INSTALL) -f $(BINDIR) pppdump
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppdump.8
