#
# Makefile for chat on Solaris 2
#

include ../svr4/Makedefs

CFLAGS = -DNO_USLEEP $(COPTS)

all:	chat

chat: chat.o
	$(CC) -o chat chat.o

install: chat
	$(INSTALL) -f $(BINDIR) chat
	$(INSTALL) -m 444 -f $(MANDIR)/man8 chat.8

clean:
	rm -f *~ *.o chat
