#
# Makefile for plugins on Solaris 2
#
# $Id: Makefile.sol2,v 1.1 1999/09/16 01:17:00 masputra Exp $
#

include ../../svr4/Makedefs

CFLAGS	= -c -O -I.. -I../../include $(COPTS)
LDFLAGS	= -G 

all:	minconn.so

minconn.so: minconn.o
	ld -o $@ $(LDFLAGS) -h $@ minconn.o

minconn.o: minconn.c
	$(CC) $(CFLAGS) -c $? 

clean:
	rm -f *.o *.so
