# ppp top level makefile for NeXT systems
#
# $Id: Makefile.top,v 1.6 1999/03/31 06:07:56 paulus Exp $
#

# Change the values of ARCHFLAGS to include the 
# appropriate architectures.  A blank entry compiles
# for the local architecture
#ARCHFLAGS = -arch i386 -arch m68k -arch hppa -arch sparc
#ARCHFLAGS = -arch i386 -arch m68k
ARCHFLAGS =

#
# It is not suggested that you change any values from here
# on.
#
BINDIR = /usr/local/ppp/bin
MANDIR = /usr/local/ppp/man
ETCDIR = /etc/ppp


all:
	cd NeXT/libposix; $(MAKE) ARCHFLAGS="$(ARCHFLAGS)" all
	cd chat; $(MAKE) -f Makefile.NeXT ARCHFLAGS="$(ARCHFLAGS)" all
	cd pppstats; $(MAKE) -f Makefile.NeXT ARCHFLAGS="$(ARCHFLAGS)" all
	cd pppd; $(MAKE) -f Makefile.NeXT ARCHFLAGS="$(ARCHFLAGS)" all
	cd NeXT; $(MAKE) ARCHFLAGS="$(ARCHFLAGS)" all


install: 
	cd chat; \
	$(MAKE) -f Makefile.NeXT ARCHFLAGS="$(ARCHFLAGS)" BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd pppstats; \
	$(MAKE) -f Makefile.NeXT ARCHFLAGS="$(ARCHFLAGS)" BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd pppd; \
	$(MAKE) -f Makefile.NeXT ARCHFLAGS="$(ARCHFLAGS)" BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd NeXT; \
	$(MAKE) ARCHFLAGS="$(ARCHFLAGS)" BINDIR=$(BINDIR) ETCDIR=$(ETCDIR) install

clean: 
	rm -f *~
	(cd libposix; $(MAKE) -f Makefile.NeXT clean)
	(cd chat; $(MAKE) -f Makefile.NeXT clean)
	(cd pppstats; $(MAKE) -f Makefile.NeXT clean)
	(cd pppd; $(MAKE) -f Makefile.NeXT clean)
	(cd NeXT; $(MAKE) clean)



NEXTTOP = \
	README.NeXT				\
	${NULL}

NEXTPOSIX = \
	libposix/Makefile.NeXT			\
	libposix/libposix.c			\
	${NULL}

NEXTPPPD = \
	pppd/Makefile.NeXT			\
	pppd/sys-NeXT.c				\
	${NULL}

NEXTNET = \
	net/if_ppp.h				\
	net/ppp_defs.h				\
	${NULL}

NEXTSTATS = \
	pppstats/Makefile.NeXT			\
	${NULL}

#	pppstats/pppstats.c			


NEXTCHAT = \
	chat/Makefile.NeXT			\
	chat/chat.c.3.2				\
	${NULL}

NEXTLKS = \
	NeXT/ChangeLog.rtf			\
	NeXT/INSTALL				\
	NeXT/Load_Commands.sect			\
	NeXT/Makefile				\
	NeXT/Makefile.top			\
        NeXT/NeXT_Version.h			\
	NeXT/TODO.NeXT				\
	NeXT/Unload_Commands.sect		\
	NeXT/bsd-comp.c				\
	NeXT/if_ppp.c				\
	NeXT/if_pppvar.h			\
	NeXT/inlines.h				\
	NeXT/linedisc.h				\
	NeXT/nbq.h				\
	NeXT/netbuf.h				\
	NeXT/ppp_tty.c				\
	NeXT/spl.h				\
	NeXT/vjcompress.c			\
	${NULL}

NEXTHPPA = \
	NeXT/hppa/README.hppa			\
	NeXT/hppa/hppaSerialPatch.tar.gz	\
	${NULL}

NEXTMACH = \
	NeXT/mach/features.h			\
	${NULL}


NEXTEXAMP = \
	NeXT/Examples/NXHosting_with_PPP	\
	NeXT/Examples/Persistent_Connection	\
	NeXT/Examples/README			\
	NeXT/Examples/chap-secrets.example	\
	NeXT/Examples/flow-control-hints	\
	NeXT/Examples/ip-down.example		\
	NeXT/Examples/ip-up.example		\
	NeXT/Examples/options.example		\
	NeXT/Examples/pap-secrets.example	\
	NeXT/Examples/ppp_multiple_hosts.tar.gz	\
	NeXT/Examples/pppdown			\
	NeXT/Examples/pppkill.c			\
	NeXT/Examples/pppup.annex		\
	NeXT/Examples/pppup.direct		\
	NeXT/Examples/pppup.portmaster		\
	NeXT/Examples/pppup.remote		\
	NeXT/Examples/pppup.zyxel		\
	NeXT/Examples/redial.sh			\
	${NULL}

NEXTPORT = \
	   ${NEXTTOP}			\
	   ${NEXTPOSIX}			\
	   ${NEXTPPPD}			\
	   ${NEXTNET}			\
	   ${NEXTSTATS}			\
	   ${NEXTCHAT}			\
	   ${NEXTLKS}			\
	   ${NEXTHPPA}			\
	   ${NEXTMACH}			\
	   ${NEXTEXAMP}			\
	   ${NULL}


#
#  The idea is to make for easy distribution of new port material.
#  Just make sure all relevant files appear in the lists above,
#  then:
#    1) Update the file ./NeXT_Version with a new number
#    2) go to the top level directory and type 'make portdist'.
#       You should get a nice tared/compressed file that is ready for
#       the archive. 
#

portdist: 
	echo NeXT-ppp2.3.7-`sed -e '/version_string/!d' \
             -e 's/[^0-9.]*\([0-9.]*\).*/\1/' -e q ./NeXT/NeXT_Version.h` > .fname
	rm -rf `cat .fname`
	mkdir `cat .fname`
	mkdir `cat .fname`/libposix
	mkdir `cat .fname`/pppd
	mkdir `cat .fname`/net
	mkdir `cat .fname`/chat
	mkdir `cat .fname`/NeXT
	mkdir `cat .fname`/NeXT/hppa
	mkdir `cat .fname`/NeXT/mach
	mkdir `cat .fname`/NeXT/Examples
	mkdir `cat .fname`/pppstats
	-ln $(NEXTTOP) `cat .fname`
	-ln $(NEXTPOSIX) `cat .fname`/libposix
	-ln $(NEXTPPPD) `cat .fname`/pppd
	-ln $(NEXTNET) `cat .fname`/net
	-ln $(NEXTCHAT) `cat .fname`/chat
	-ln $(NEXTLKS) `cat .fname`/NeXT
	-ln $(NEXTHPPA) `cat .fname`/NeXT/hppa
	-ln $(NEXTMACH) `cat .fname`/NeXT/mach
	-ln $(NEXTEXAMP) `cat .fname`/NeXT/Examples
	-ln $(NEXTSTATS) `cat .fname`/pppstats
	for file in $(NEXTPORT); do \
		test -r `cat .fname`/$$file || cp -p $$file `cat .fname`; \
	done
	(cd `cat .fname`;tar chf - '.' | gzip --best > ../`cat ../.fname`.tar.gz)
	rm -rf `cat .fname` .fname

.PHONY: dialppp portdist
