#
# pppstats makefile
# $Id: Makefile.ultrix,v 1.3 1995/04/28 06:23:39 paulus Exp $
#

PPPSTATSRCS = pppstats.c
PPPSTATOBJS = pppstats.o

#CC = gcc
COPTS = -O
COMPILE_FLAGS = 
LIBS = 

CFLAGS = -I.. $(COPTS) $(COMPILE_FLAGS)

all: pppstats

install: pppstats
	install -c pppstats $(BINDIR)/pppstats

pppstats: $(PPPSTATSRCS)
	$(CC) $(CFLAGS) -o pppstats pppstats.c $(LIBS)

clean:
	rm -f pppstats *~ #* core

depend:
	cpp -M $(CFLAGS) $(PPPSTATSRCS) >.depend
#	makedepend $(CFLAGS) $(PPPSTATSRCS)
