#	$Id: Makefile.bsd,v 1.2 1994/04/25 06:48:25 paulus Exp $

PROG=	pppstats
SRCS=	pppstats.c
CFLAGS+=-I..
LDADD=	-lutil -lkvm
NOMAN=	noman
BINMODE=2555
BINGRP=	kmem
BINDIR=	/usr/sbin

.include <bsd.prog.mk>
