#
# pppstats makefile
#

PPPSTATSRCS = pppstats.c
PPPSTATOBJS = pppstats.o

#CC = gcc
COPTS = -O
COMPILE_FLAGS = -DSTREAMS
LIBS =

CFLAGS = -I.. $(COPTS) $(COMPILE_FLAGS)

all: pppstats

install: pppstats
	installbsd -c pppstats $(BINDIR)/pppstats

pppstats: $(PPPSTATSRCS)
	$(CC) $(CFLAGS) -o pppstats pppstats.c $(LIBS)

clean:
	rm -f pppstats *~ #* core

depend:
	cpp -M $(CFLAGS) $(PPPSTATSRCS) >.depend
#	makedepend $(CFLAGS) $(PPPSTATSRCS)
