#	$Id: Makefile.bsd,v 1.6 1998/03/25 02:21:18 paulus Exp $

PROG=	pppstats
SRCS=	pppstats.c
CFLAGS+=-I../include -D_BITYPES
MAN8=	pppstats.8
MAN=	pppstats.cat8
BINDIR=	/usr/sbin

.include <bsd.prog.mk>
