#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.sol2,v 1.5 1996/09/14 05:12:45 paulus Exp $
#

BINDIR = /usr/local/bin
MANDIR = /usr/local/man
INSTALL = /usr/sbin/install

# For gcc
#CC = gcc
#COPTS = -g -O

# For sun c
COPTS = -O -Xa

CFLAGS = -I.. $(COPTS) -DSTREAMS

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
