#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.svr4,v 1.4 1996/09/26 06:16:18 paulus Exp $
#

BINDIR = /usr/local/bin
MANDIR = /usr/local/man
INSTALL = /usr/sbin/install

#CC = gcc
#COPTS = -O

COPTS = -O -Xa

CFLAGS = -DSTREAMS -I.. $(COPTS)

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
