#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.svr4,v 1.5 1998/02/04 01:41:47 paulus Exp $
#

include ../svr4/Makedefs

CFLAGS = -DSTREAMS -I.. $(COPTS)

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
