#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.sol2,v 1.2 1996/04/04 04:09:03 paulus Exp $
#

BINDIR = /usr/local/bin
MANDIR = /usr/local/man
INSTALL = /usr/sbin/install

# For gcc
#CC = gcc
#COPTS = -g -O

# For sun c
COPTS = -g -Xa -w -D__svr4__

CFLAGS = -I.. $(COPTS)

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
