#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.sol2,v 1.1 1995/10/27 03:54:26 paulus Exp $
#

BINDIR = /usr/local/bin
MANDIR = /usr/local/man
INSTALL = /usr/sbin/install

CC = gcc
COPTS = -g -O
CFLAGS = -I.. $(COPTS)

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
