#!/bin/sh
#
# A program or script which is executed when the link goes down, if the remote
# system successfully authenticates itself. It is executed with the parameters
# <interface-name> <peer-name> <user-name> <tty-device> <speed> <ipparam>
#

#
# The environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

echo auth-down `date +'%y/%m/%d %T'` $* >> /var/log/pppstats

# last line
