#
# libposix makefile
# $Id: Makefile,v 1.1 1998/03/26 02:52:03 paulus Exp $
#

ARCHFLAGS = 

SRCS = libposix.c
OBJS = libposix.o

CFLAGS = -O -D_POSIX_SOURCE $(ARCHFLAGS)

all: $(OBJS)

clean:
	rm -f *.o *~ core

