# PPP top-level Makefile for Linux.

DESTDIR = @DESTDIR@
BINDIR = $(DESTDIR)/sbin
INCDIR = @INCDIR@
MANDIR = $(DESTDIR)/share/man
ETCDIR = @SYSCONF@/ppp

# uid 0 = root
INSTALL= install

all:
	cd chat; $(MAKE) $(MFLAGS) all
	cd pppd/plugins; $(MAKE) $(MFLAGS) all
	cd pppd; $(MAKE) $(MFLAGS) all
	cd pppstats; $(MAKE) $(MFLAGS) all
	cd pppdump; $(MAKE) $(MFLAGS) all

install: $(INSTROOT)$(BINDIR) $(INSTROOT)$(MANDIR)/man8 install-progs install-devel

install-progs:
	cd chat; $(MAKE) $(MFLAGS) install
	cd pppd/plugins; $(MAKE) $(MFLAGS) install
	cd pppd; $(MAKE) $(MFLAGS) install
	cd pppstats; $(MAKE) $(MFLAGS) install
	cd pppdump; $(MAKE) $(MFLAGS) install

install-etcppp: $(INSTROOT)$(ETCDIR) $(INSTROOT)$(ETCDIR)/options $(INSTROOT)$(ETCDIR)/pap-secrets \
	$(INSTROOT)$(ETCDIR)/chap-secrets

install-devel:
	cd pppd; $(MAKE) $(MFLAGS) install-devel

$(INSTROOT)$(ETCDIR)/options:
	$(INSTALL) -c -m 644 etc.ppp/options $@
$(INSTROOT)$(ETCDIR)/pap-secrets:
	$(INSTALL) -c -m 600 etc.ppp/pap-secrets $@
$(INSTROOT)$(ETCDIR)/chap-secrets:
	$(INSTALL) -c -m 600 etc.ppp/chap-secrets $@

$(INSTROOT)$(BINDIR):
	$(INSTALL) -d -m 755 $@
$(INSTROOT)$(MANDIR)/man8:
	$(INSTALL) -d -m 755 $@
$(INSTROOT)$(ETCDIR):
	$(INSTALL) -d -m 755 $@

clean:
	rm -f `find . -name '*.[oas]' -print`
	rm -f `find . -name 'core' -print`
	rm -f `find . -name '*~' -print`
	cd chat; $(MAKE) clean
	cd pppd/plugins; $(MAKE) clean
	cd pppd; $(MAKE) clean
	cd pppstats; $(MAKE) clean
	cd pppdump; $(MAKE) clean

dist-clean:	clean
	rm -f Makefile `find . -name Makefile -print`

#kernel:
#	cd linux; ./kinstall.sh

# no tests yet, one day...
installcheck:
	true
