#
# ppp top level makefile
#

BINDIR = /usr/local/etc
MANDIR = /usr/local/man

all:
	cd chat; $(MAKE) all
	cd pppd; $(MAKE) all
	cd pppstats; $(MAKE) all

install:
	cd chat; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd pppd; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	cd pppstats; $(MAKE) BINDIR=$(BINDIR) MANDIR=$(MANDIR) install
	@( release=`uname -r` ;\
	  case $${release} in \
         	V[123].*) sdir="/sys/streamsm"; \
			  idir="/sys/include/net";; \
         	V[4-9]*)  sdir="/usr/sys/BINARY/streamsm"; \
			  idir="/usr/sys/include/net";; \
    	  esac; \
	  mkdir -p $${sdir}; \
	  mkdir -p $${idir}; \
	  cd osf1; $(MAKE) STREAMSDIR=$${sdir} INCLNETDIR=$${idir} install ;)

clean:
	rm -f *~
	cd chat; $(MAKE) clean
	cd pppd; $(MAKE) clean
	cd pppstats; $(MAKE) clean

