name: Buildroot
on: [push, pull_request]

jobs:
  buildroot:
    name: Buildroot
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        defconfig_name: [qemu_x86_defconfig, qemu_x86_64_defconfig, raspberrypi4_defconfig, raspberrypi4_64_defconfig, qemu_ppc64le_pseries_defconfig, qemu_mips32r2_malta_defconfig, qemu_mips64_malta_defconfig]
        libc_name: [glibc, uclibc, musl]
    env:
      PPP_CI_VERSION: v1.0
      BUILDROOT_DIRECTORY_NAME: buildroot-${{ matrix.defconfig_name }}-${{ matrix.libc_name }}
    steps:
      - name: Retrieve prebuilt Buildroot image...
        working-directory: /home/runner
        run: |
          wget https://github.com/ppp-project/ppp-ci/releases/download/${{ env.PPP_CI_VERSION }}/${{ env.BUILDROOT_DIRECTORY_NAME }}.tar.zst
          tar -xf ${{ env.BUILDROOT_DIRECTORY_NAME }}.tar.zst
      - name: Select latest PPP upstream version
        working-directory: /home/runner/${{ env.BUILDROOT_DIRECTORY_NAME }}/package/pppd
        run: |
          # Get package sources from head of current branch
          sed -i "/PPPD_VERSION =/c\\PPPD_VERSION = ${GITHUB_SHA}" pppd.mk
      - name: Trigger a PPP package rebuild
        working-directory: /home/runner/${{ env.BUILDROOT_DIRECTORY_NAME }}/output/build
        run: rm -rf pppd*
      - name: Build
        working-directory: /home/runner/${{ env.BUILDROOT_DIRECTORY_NAME }}
        run: make
