#	$Id: Makefile.bsd,v 1.11 1996/07/01 05:31:47 paulus Exp $

BINDIR?= /usr/sbin
CFLAGS+= -g -I.. -DHAVE_PATHS_H

PROG=	pppd
SRCS=	main.c magic.c fsm.c lcp.c ipcp.c upap.c chap.c md5.c ccp.c \
	demand.c auth.c options.c sys-bsd.c
MAN=	pppd.cat8
# The next line is for NetBSD-1.0 and other older *BSD systems.
MAN8=	pppd.0
BINMODE=4555
BINOWN=	root

LDADD=	-lcrypt -lutil
DPADD=	${LIBCRYPT} ${LIBUTIL}

.include <bsd.prog.mk>
