#	$Id: Makefile.bsd,v 1.2 1993/12/14 05:11:53 paulus Exp $

COPTS?= -g
CFLAGS+= -DDEBUGALL

PROG=	pppd
SRCS=	main.c magic.c fsm.c lcp.c ipcp.c upap.c chap.c md5.c \
	auth.c options.c sys-bsd.c
MAN8=	pppd.0
BINMODE=4555
BINOWN=	root

LDADD=	-lcrypt -lutil
DPADD=	${LIBCRYPT} ${LIBUTIL}

.include <bsd.prog.mk>
