#
# Makefile for pppd under SunOS 4.
# $Id: Makefile.sunos4,v 1.8 1998/03/25 01:27:06 paulus Exp $
#

include ../sunos4/Makedefs

LIBS =

CFLAGS = $(COPTS) -I../include -DSUNOS4

all: pppd

OBJS = main.o magic.o fsm.o lcp.o ipcp.o upap.o chap.o md5.o ccp.o \
	auth.o options.o demand.o sys-sunos4.o

pppd:	$(OBJS)
	$(CC) -o pppd $(OBJS) $(LIBS)

install:
	$(INSTALL) -c -m 4555 pppd $(BINDIR)/pppd
	$(INSTALL) -c -m 444 pppd.8 $(MANDIR)/man8/pppd.8

clean:
	rm -f $(OBJS) pppd *~ core
